In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('IST_MIR.csv')
dataset = df[['URL','File','Lines_of_code','Require','Ensure','Include','Attribute','Hard_coded_string','Comment','Command','File_mode','SSH_KEY','defect_status']]
#df = dataset[df_properties]

In [3]:
dataset.head()

URL  File  Lines_of_code  Require  Ensure  Include  Attribute  \
0    0     0            125        0       0        0         27   
1    1     1             35        0       1        1          6   
2    0     2             53        0       3        5         19   
3    0     0              1        0       0        1          0   
4    0     2            278        6       4       11         54   

   Hard_coded_string  Comment  Command  File_mode  SSH_KEY  defect_status  
0                 16       32        0          0        0              0  
1                 10       11        1          1        1              1  
2                 15        0        2          1        1              1  
3                  0        0        0          0        0              1  
4                 30       96        4          1        1              0

In [6]:
dataset.keys()
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 12].values

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.1)

In [8]:
X_train

array([[  0,   0,   0, ...,   0,   0,   0],
       [  1,   0,  12, ...,   0,   0,   0],
       [  0,   0,  46, ...,   0,   0,   0],
       ...,
       [  0,   0,  19, ...,   0,   0,   0],
       [  0,   0, 125, ...,   0,   0,   0],
       [  0,   0,  70, ...,   0,   0,   0]], dtype=int64)

In [14]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
print(X_train)
pca = PCA(n_components=1)
pca.fit(X_train)
X_train_PCA = pca.transform(X_train)
X_test_PCA = pca.transform(X_test)
print(X_train_PCA)

[[-0.42862113 -0.49286757 -0.71305181 ... -0.40064951 -0.50872518
  -0.51674692]
 [ 0.36043141 -0.49286757 -0.62474931 ... -0.40064951 -0.50872518
  -0.51674692]
 [-0.42862113 -0.49286757 -0.37455888 ... -0.40064951 -0.50872518
  -0.51674692]
 ...
 [-0.42862113 -0.49286757 -0.57323951 ... -0.40064951 -0.50872518
  -0.51674692]
 [-0.42862113 -0.49286757  0.20676595 ... -0.40064951 -0.50872518
  -0.51674692]
 [-0.42862113 -0.49286757 -0.19795387 ... -0.40064951 -0.50872518
  -0.51674692]]
[[-1.95381291e+00]
 [-1.74346448e+00]
 [-1.18483825e+00]
 [ 2.14707237e+00]
 [-1.07893601e+00]
 [ 2.47715788e+00]
 [ 2.21197921e+00]
 [-1.35668074e+00]
 [-1.81606993e+00]
 [-1.63344611e+00]
 [-1.33832192e+00]
 [-1.40049090e+00]
 [-1.77524285e+00]
 [-1.91561134e+00]
 [-1.91561134e+00]
 [-3.68615808e-01]
 [ 1.70501852e+01]
 [ 2.08977803e+00]
 [ 4.30824275e-03]
 [-1.28232534e+00]
 [ 1.22838790e+00]
 [ 7.34454757e-01]
 [-1.55915377e+00]
 [ 5.67849165e-01]
 [ 8.88238391e+00]
 [ 2.53747646e-01]
 [-1.91561134e

In [15]:
print(X_train_PCA)

[[-1.95381291e+00]
 [-1.74346448e+00]
 [-1.18483825e+00]
 [ 2.14707237e+00]
 [-1.07893601e+00]
 [ 2.47715788e+00]
 [ 2.21197921e+00]
 [-1.35668074e+00]
 [-1.81606993e+00]
 [-1.63344611e+00]
 [-1.33832192e+00]
 [-1.40049090e+00]
 [-1.77524285e+00]
 [-1.91561134e+00]
 [-1.91561134e+00]
 [-3.68615808e-01]
 [ 1.70501852e+01]
 [ 2.08977803e+00]
 [ 4.30824275e-03]
 [-1.28232534e+00]
 [ 1.22838790e+00]
 [ 7.34454757e-01]
 [-1.55915377e+00]
 [ 5.67849165e-01]
 [ 8.88238391e+00]
 [ 2.53747646e-01]
 [-1.91561134e+00]
 [-7.70613554e-01]
 [-1.64094156e+00]
 [-1.91109685e+00]
 [ 1.33151843e+00]
 [-1.91561134e+00]
 [ 1.39555055e+00]
 [-3.68215092e-01]
 [ 3.62492007e+00]
 [ 5.83139405e+00]
 [-6.04933557e-01]
 [-1.68016774e+00]
 [-1.81425725e+00]
 [ 3.90839375e+00]
 [-1.31476525e+00]
 [-4.95909021e-01]
 [-1.57488527e+00]
 [ 7.06896135e-01]
 [-1.23174699e+00]
 [-1.38041575e+00]
 [-1.33625018e+00]
 [ 6.90740559e-02]
 [-1.40455295e+00]
 [ 5.90536404e+00]
 [ 1.94574126e-01]
 [-1.08040915e+00]
 [ 4.6788778

In [16]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train_PCA,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [17]:
y_pred = classifier.predict(X_test_PCA)

In [73]:
aaa = 'cxs'
 

no


In [18]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
print(classification_report(y_test,y_pred))
print(roc_auc_score(y_test, y_pred))
#print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.62      0.56      0.59         9
           1       0.60      0.67      0.63         9

    accuracy                           0.61        18
   macro avg       0.61      0.61      0.61        18
weighted avg       0.61      0.61      0.61        18

0.6111111111111112
